class StudyBuddy {
    constructor() { this.db = null; this.data = null; this.currentSemesterId = null; this.selectedSubjectId = null; this.init(); }
    async init() { await this.initDB(); this.attachEventListeners(); this.setupTabs(); if (this.data?.semesters.length) { this.currentSemesterId = this.data.semesters[0].id; this.renderSemesterSelector(); this.renderSubjects(); this.loadSemesterNotebook(); } else { this.renderSemesterSelector(); this.renderSubjects(); } this.updateStats(); this.showToast('🐻‍❄️ Ready! Global semester notebook added 💖'); }
    initDB() { return new Promise((resolve) => { const request = indexedDB.open('StudyBuddyDB', 5); request.onerror = () => { this.data = this.getDefaultData(); this.saveToLocalStorage(); resolve(); }; request.onsuccess = (event) => { this.db = event.target.result; this.loadDataFromDB().then(() => resolve()); }; request.onupgradeneeded = (event) => { const db = event.target.result; if (!db.objectStoreNames.contains('appData')) db.createObjectStore('appData', { keyPath: 'id' }); if (!db.objectStoreNames.contains('files')) { const fileStore = db.createObjectStore('files', { keyPath: 'id' }); fileStore.createIndex('subjectId', 'subjectId', { unique: false }); } }; }); }
    loadDataFromDB() { return new Promise((resolve) => { if (!this.db) { this.data = this.getDefaultData(); resolve(); return; } const transaction = this.db.transaction(['appData'], 'readonly'); const request = transaction.objectStore('appData').get('mainData'); request.onsuccess = () => { this.data = (request.result && request.result.data) ? request.result.data : this.getDefaultData(); resolve(); }; request.onerror = () => { this.data = this.getDefaultData(); resolve(); }; }); }
    saveDataToDB() { return new Promise((resolve) => { if (!this.db) { this.saveToLocalStorage(); this.updateStats(); resolve(); return; } const transaction = this.db.transaction(['appData'], 'readwrite'); transaction.objectStore('appData').put({ id: 'mainData', data: this.data }); transaction.oncomplete = () => { this.updateStats(); resolve(); }; transaction.onerror = () => { this.saveToLocalStorage(); this.updateStats(); resolve(); }; }); }
    saveToLocalStorage() { localStorage.setItem('studyBuddyBackup', JSON.stringify(this.data)); }
    getDefaultData() { const now = Date.now(); return { version: "3.0", semesters: [{ id: now, name: "🌸 Spring 2025", semesterNotebook: "🌟 My semester goals: Stay consistent, review weekly, and enjoy learning!", subjects: [{ id: now+1, name: "Cozy UX Design", completion: "Project only", files: [], overallSubjectNotes: "Make interfaces feel like a hug 💌", notebookNotes: "🎨 User research is key. Always prototype first.", createdAt: new Date().toISOString() }, { id: now+2, name: "Creative Coding", completion: "Exam + Project", files: [], overallSubjectNotes: "p5.js + fun animations", notebookNotes: "💡 Remember: coordinates, loops, and interactivity.", createdAt: new Date().toISOString() }], createdAt: new Date().toISOString() }] }; }
    updateStats() { const totalSemesters = document.getElementById('totalSemesters'); const totalSubjects = document.getElementById('totalSubjects'); if (totalSemesters && this.data) { totalSemesters.textContent = this.data.semesters.length; const total = this.data.semesters.reduce((sum, s) => sum + s.subjects.length, 0); totalSubjects.textContent = total; } }
    showToast(msg) { const toast = document.getElementById('toast'); if (!toast) return; toast.textContent = msg + " 🧸"; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2500); }
    getCurrentSemester() { return this.data?.semesters.find(s => s.id === this.currentSemesterId); }
    getSubject(subjectId) { const sem = this.getCurrentSemester(); return sem?.subjects.find(s => s.id === subjectId); }
    detectLanguage(filename) { const ext = filename.split('.').pop().toLowerCase(); const map = { js:'JavaScript', py:'Python', java:'Java', cpp:'C++', html:'HTML', css:'CSS', pdf:'PDF', jpg:'Image', png:'Image', txt:'Text', md:'Markdown', ppt:'PPT', pptx:'PPT', json:'JSON', xml:'XML' }; return map[ext] || '📄 File'; }
    formatSize(bytes) { if (!bytes) return '0 B'; if (bytes < 1024) return bytes + ' B'; if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB'; return (bytes / 1048576).toFixed(1) + ' MB'; }
    escape(str) { if (!str) return ''; return String(str).replace(/[&<>]/g, m => m === '&' ? '&amp;' : m === '<' ? '&lt;' : '&gt;'); }
    async saveFileToDB(file, subjectId) { if (!this.db) return; this.db.transaction(['files'], 'readwrite').objectStore('files').put({ id: file.id, subjectId, name: file.name, size: file.size, type: file.type, data: file.data, summaryNotes: file.summaryNotes || '', uploadedAt: file.uploadedAt }); }
    async getFileFromDB(fileId) { if (!this.db) return null; return new Promise(resolve => { const req = this.db.transaction(['files'], 'readonly').objectStore('files').get(fileId); req.onsuccess = () => resolve(req.result); req.onerror = () => resolve(null); }); }
    async deleteFileFromDB(fileId) { if (!this.db) return; this.db.transaction(['files'], 'readwrite').objectStore('files').delete(fileId); }
    async viewFile(file) { if (!file?.id) { this.showToast('No file content'); return; } const fileData = await this.getFileFromDB(file.id); if (!fileData?.data) { this.showToast('File data missing'); return; } const modal = document.getElementById('fileViewerModal'), modalTitle = document.getElementById('modalTitle'), modalBody = document.getElementById('modalBody'); modalTitle.textContent = `📄 ${this.escape(fileData.name)}`; modalBody.innerHTML = '<div style="text-align:center; padding:2rem;">🌸 loading...</div>'; modal.style.display = 'flex'; const fileName = fileData.name.toLowerCase(), isImage = fileName.match(/\.(jpg|jpeg|png|gif|webp)$/i), isPdf = fileName.endsWith('.pdf'), isText = fileName.match(/\.(txt|js|py|java|html|css|json|md|xml|cpp|c|sql)$/i); let html = `<div style="background:#fef2f6; border-radius:32px; padding:1rem; margin-bottom:1rem;"><strong>📝 Your Summary for this file:</strong><br>${fileData.summaryNotes ? this.escape(fileData.summaryNotes) : '<em>no summary yet 🌙</em>'}</div><hr>`; if (isImage) html += `<img src="${fileData.data}" style="max-width:100%; border-radius:32px;">`; else if (isPdf) html += `<embed src="${fileData.data}" type="application/pdf" width="100%" height="500px">`; else if (isText) { try { let text = fileData.data; if (text.startsWith('data:')) { const b64 = text.split(',')[1]; if (b64) text = atob(b64); } html += `<pre style="background:#1e1a2a; color:#fcd5e6; padding:1rem; border-radius:24px; overflow-x:auto;">${this.escape(text)}</pre>`; } catch(e) { html += `<p>Could not preview</p>`; } } else html += `<div style="text-align:center"><a href="${fileData.data}" download="${this.escape(fileData.name)}" class="btn-gradient" style="display:inline-block; margin-top:1rem;">⬇️ Download</a></div>`; modalBody.innerHTML = html; }
    closeModals() { document.getElementById('fileViewerModal').style.display = 'none'; document.getElementById('filesByLanguageModal').style.display = 'none'; }
    renderSemesterSelector() { const selector = document.getElementById('semesterSelector'); if (!selector || !this.data) return; selector.innerHTML = '<option value="">✨ choose semester ✨</option>'; this.data.semesters.forEach(sem => { const opt = document.createElement('option'); opt.value = sem.id; opt.textContent = `${sem.name} (${sem.subjects.length} subjects)`; if (this.currentSemesterId === sem.id) opt.selected = true; selector.appendChild(opt); }); }
    renderSubjects() { const container = document.getElementById('subjectsList'); const sem = this.getCurrentSemester(); if (!container) return; if (!sem || !sem.subjects.length) { container.innerHTML = '<div style="text-align:center; padding:2rem;">🍬 add your first subject! 🍬</div>'; return; } container.innerHTML = sem.subjects.map(sub => `<div class="subject-bubble ${this.selectedSubjectId === sub.id ? 'selected' : ''}" data-id="${sub.id}"><div><span class="subject-name-cute"><i class="fas fa-book"></i> ${this.escape(sub.name)}</span><span class="badge-completion">${sub.completion}</span></div><div class="subject-actions"><button class="mini-btn select-subj" data-id="${sub.id}">📖 Select</button><button class="mini-btn edit edit-subject" data-id="${sub.id}" data-name="${this.escape(sub.name)}" data-completion="${sub.completion}">✏️ Edit</button><button class="mini-btn danger delete-subj" data-id="${sub.id}">🗑️</button></div></div>`).join(''); document.querySelectorAll('.select-subj').forEach(btn => btn.addEventListener('click', (e) => { e.stopPropagation(); this.selectedSubjectId = parseInt(btn.dataset.id); this.renderSubjects(); this.renderSubjectDetail(); })); document.querySelectorAll('.delete-subj').forEach(btn => btn.addEventListener('click', (e) => { e.stopPropagation(); this.deleteSubject(parseInt(btn.dataset.id)); })); document.querySelectorAll('.edit-subject').forEach(btn => btn.addEventListener('click', (e) => { e.stopPropagation(); this.editSubjectPrompt(parseInt(btn.dataset.id), btn.dataset.name, btn.dataset.completion); })); }
    editSubjectPrompt(id, oldName, oldComp) { const newName = prompt("Edit subject name:", oldName); if (newName?.trim()) { const newComp = prompt("Completion type (Exam only / Project only / Exam + Project):", oldComp); if (newComp && ["Exam only","Project only","Exam + Project"].includes(newComp)) { const sub = this.getSubject(id); if (sub) { sub.name = newName.trim(); sub.completion = newComp; this.saveDataToDB(); this.renderSubjects(); if (this.selectedSubjectId === id) this.renderSubjectDetail(); this.showToast("Subject updated"); } } else this.showToast("Invalid completion type"); } }
    async deleteSubject(id) { if (confirm('⚠️ Delete this subject? All files and notes will be gone forever. 🥺')) { const sem = this.getCurrentSemester(); const subject = sem.subjects.find(s => s.id === id); if (subject?.files) for (const file of subject.files) await this.deleteFileFromDB(file.id); sem.subjects = sem.subjects.filter(s => s.id !== id); if (this.selectedSubjectId === id) { this.selectedSubjectId = null; document.getElementById('subjectFilesArea').style.display = 'none'; document.getElementById('selectedSubjectInfo').innerHTML = '<div style="padding:1rem;">🌸 pick a subject</div>'; } await this.saveDataToDB(); this.renderSubjects(); this.showToast('subject deleted'); } }
    renderSubjectDetail() { const sub = this.getSubject(this.selectedSubjectId); const infoDiv = document.getElementById('selectedSubjectInfo'), areaDiv = document.getElementById('subjectFilesArea'); if (!sub) { if (infoDiv) infoDiv.innerHTML = '<div style="padding:1rem;">🍬 select a subject first 🧸</div>'; if (areaDiv) areaDiv.style.display = 'none'; return; } if (infoDiv) infoDiv.innerHTML = `<div style="background:#fff0f5; border-radius:60px; padding:0.8rem;"><strong>📘 ${this.escape(sub.name)}</strong> · ${sub.completion} · ${sub.files?.length || 0} files</div>`; if (areaDiv) areaDiv.style.display = 'block'; const notesArea = document.getElementById('subjectOverallNotes'); if (notesArea) notesArea.value = sub.overallSubjectNotes || ''; const notebookArea = document.getElementById('subjectNotebook'); if (notebookArea) notebookArea.value = sub.notebookNotes || ''; this.renderFiles(); }
    async renderFiles() { const sub = this.getSubject(this.selectedSubjectId); const container = document.getElementById('filesList'); if (!container || !sub) return; if (!sub.files?.length) { container.innerHTML = '<div style="text-align:center;padding:1rem;">📎 no files yet, upload sweet notes 💗</div>'; return; } container.innerHTML = sub.files.map((f, idx) => `<div class="file-card"><div><i class="fas fa-paperclip"></i> ${this.escape(f.name)} <span style="background:#f0e6ff; border-radius:30px; padding:0.1rem 0.5rem;">${this.detectLanguage(f.name)}</span> <small>${this.formatSize(f.size)}</small></div><textarea class="file-summary-input" data-idx="${idx}" rows="1" placeholder="add cute summary ..." style="width:100%; border-radius:40px; margin:5px 0; padding:0.5rem;">${this.escape(f.summaryNotes || '')}</textarea><div style="display:flex; gap:6px;"><button class="pill-btn save-summary-btn" data-idx="${idx}">💾 Save summary</button><button class="pill-btn view-file-btn" data-idx="${idx}" style="background:#c9d9ff;">👁️ View</button><button class="pill-btn delete-file-btn" data-idx="${idx}" style="background:#ffe0e0;">❌ Delete</button></div></div>`).join(''); for (let btn of container.querySelectorAll('.save-summary-btn')) btn.addEventListener('click', async (e) => { const idx = parseInt(btn.dataset.idx); const ta = container.querySelector(`.file-summary-input[data-idx="${idx}"]`); if (ta && sub.files[idx]) { sub.files[idx].summaryNotes = ta.value; const fileData = await this.getFileFromDB(sub.files[idx].id); if (fileData) { fileData.summaryNotes = ta.value; this.db?.transaction(['files'], 'readwrite').objectStore('files').put(fileData); } await this.saveDataToDB(); this.showToast('file summary saved!'); } }); for (let btn of container.querySelectorAll('.view-file-btn')) btn.addEventListener('click', async () => { const idx = parseInt(btn.dataset.idx); if (sub.files[idx]) await this.viewFile(sub.files[idx]); }); for (let btn of container.querySelectorAll('.delete-file-btn')) btn.addEventListener('click', async () => { if (confirm('Delete this file? 🗑️')) { const idx = parseInt(btn.dataset.idx); const fileId = sub.files[idx].id; await this.deleteFileFromDB(fileId); sub.files.splice(idx, 1); await this.saveDataToDB(); await this.renderFiles(); this.showToast('file removed'); } }); }
    addSubject(name, completion) { if (!name.trim()) { this.showToast('name pls!'); return; } const sem = this.getCurrentSemester(); if (!sem) { this.showToast('select a semester first'); return; } sem.subjects.push({ id: Date.now(), name: name.trim(), completion: completion, files: [], overallSubjectNotes: '', notebookNotes: '', createdAt: new Date().toISOString() }); this.saveDataToDB(); this.renderSubjects(); document.getElementById('newSubjectName').value = ''; this.showToast(`➕ ${name} added!`); }
    addSemester(name) { if (!name.trim()) return; this.data.semesters.push({ id: Date.now(), name: name, semesterNotebook: "", subjects: [], createdAt: new Date().toISOString() }); this.currentSemesterId = this.data.semesters[this.data.semesters.length - 1].id; this.selectedSubjectId = null; this.saveDataToDB(); this.renderSemesterSelector(); this.renderSubjects(); this.loadSemesterNotebook(); document.getElementById('subjectFilesArea').style.display = 'none'; this.showToast(`🎀 semester "${name}" created`); }
    deleteCurrentSemester() { if (!this.currentSemesterId) return; if (confirm('⚠️ Delete entire semester? This removes all subjects and files. This action is permanent.')) { this.data.semesters = this.data.semesters.filter(s => s.id !== this.currentSemesterId); this.currentSemesterId = this.data.semesters[0]?.id || null; this.selectedSubjectId = null; this.saveDataToDB(); this.renderSemesterSelector(); this.renderSubjects(); this.loadSemesterNotebook(); document.getElementById('subjectFilesArea').style.display = 'none'; this.showToast('semester gone'); } }
    editSemesterName() { const sem = this.getCurrentSemester(); if (!sem) return; const newName = prompt("Edit semester name:", sem.name); if (newName?.trim()) { sem.name = newName.trim(); this.saveDataToDB(); this.renderSemesterSelector(); this.showToast("Semester renamed"); } }
    loadSemesterNotebook() { const sem = this.getCurrentSemester(); const notebookArea = document.getElementById('semesterNotebook'); if (sem && notebookArea) { notebookArea.value = sem.semesterNotebook || ''; } }
    saveSemesterNotebook() { const sem = this.getCurrentSemester(); if (!sem) { this.showToast('No semester selected'); return; } const notebookContent = document.getElementById('semesterNotebook').value; sem.semesterNotebook = notebookContent; this.saveDataToDB(); this.showToast('📓 Semester notebook saved!'); }
    generateSummary() { const sem = this.getCurrentSemester(); if (!sem) { this.showToast('pick semester'); return; } let txt = `📚 ${sem.name} - COMPLETE SEMESTER SUMMARY 🌈\n${new Date().toLocaleString()}\n${'='.repeat(55)}\n\n`; if (sem.semesterNotebook && sem.semesterNotebook.trim()) { txt += `📓 GLOBAL SEMESTER NOTEBOOK:\n${sem.semesterNotebook}\n\n${'='.repeat(55)}\n\n`; } sem.subjects.forEach(sub => { txt += `📖 SUBJECT: ${sub.name} (${sub.completion})\n`; if (sub.overallSubjectNotes) txt += `   ✏️ Subject Notes: ${sub.overallSubjectNotes}\n`; if (sub.notebookNotes && sub.notebookNotes.trim()) txt += `   📓 Subject Notebook: ${sub.notebookNotes}\n`; if (sub.files?.length) { txt += `   📎 Files & summaries:\n`; sub.files.forEach(f => { if (f.summaryNotes) txt += `      • ${f.name}: ${f.summaryNotes}\n`; else txt += `      • ${f.name}: (no summary yet)\n`; }); } txt += '\n'; }); document.getElementById('semesterSummary').innerHTML = txt.replace(/\n/g, '<br>'); this.showToast('✨ Full semester summary generated!'); }
    exportSummary() { const sumDiv = document.getElementById('semesterSummary'); const text = sumDiv.innerText; const blob = new Blob([text], { type: 'text/plain' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `semester_summary_${Date.now()}.txt`; a.click(); URL.revokeObjectURL(a.href); }
    async openFilesByLanguage() { const sub = this.getSubject(this.selectedSubjectId); if (!sub?.files.length) { this.showToast('no files to group'); return; } const groups = {}; sub.files.forEach(f => { const lang = this.detectLanguage(f.name); if (!groups[lang]) groups[lang] = []; groups[lang].push(f); }); let html = ''; for (let lang of Object.keys(groups).sort()) { html += `<div style="margin-bottom:1.5rem;"><h4 style="background:#ffe2f0; border-radius:50px; padding:0.5rem 1rem;">🎀 ${lang} (${groups[lang].length})</h4>`; for (let f of groups[lang]) { html += `<div class="file-card" style="margin-bottom:0.7rem;"><b>${this.escape(f.name)}</b><br>${f.summaryNotes ? `💬 ${this.escape(f.summaryNotes)}` : '<i>no notes</i>'}<br><button class="pill-btn view-lang-file" data-file-id="${f.id}" style="margin-top:4px;">👀 view file</button></div>`; } html += `</div>`; } document.getElementById('langModalBody').innerHTML = html; document.getElementById('filesByLanguageModal').style.display = 'flex'; document.querySelectorAll('.view-lang-file').forEach(btn => { btn.addEventListener('click', async () => { const fileId = parseInt(btn.dataset.fileId); const found = sub.files.find(f => f.id === fileId); if (found) { await this.viewFile(found); } else { this.showToast("File not found"); } }); }); }
    saveSubjectNotebook() { if (!this.selectedSubjectId) { this.showToast('select a subject first'); return; } const sub = this.getSubject(this.selectedSubjectId); const notebookContent = document.getElementById('subjectNotebook').value; sub.notebookNotes = notebookContent; this.saveDataToDB(); this.showToast('📓 Subject notebook saved!'); }
    saveSubjectNotes() { if (!this.selectedSubjectId) return; const sub = this.getSubject(this.selectedSubjectId); const notes = document.getElementById('subjectOverallNotes').value; sub.overallSubjectNotes = notes; this.saveDataToDB(); this.showToast('Subject notes saved 🧸'); }
    async handleFileUpload(files) { if (!this.selectedSubjectId) { this.showToast('select subject first'); return; } const sub = this.getSubject(this.selectedSubjectId); if (!sub) return; if (!sub.files) sub.files = []; for (const file of Array.from(files)) { const reader = new FileReader(); const fileData = await new Promise((resolve) => { reader.onload = (e) => resolve(e.target.result); reader.readAsDataURL(file); }); const newFile = { id: Date.now() + Math.random(), name: file.name, size: file.size, type: file.type, data: fileData, summaryNotes: '', uploadedAt: new Date().toISOString() }; sub.files.push(newFile); await this.saveFileToDB(newFile, this.selectedSubjectId); await this.saveDataToDB(); this.renderFiles(); this.showToast(`🐣 ${file.name} uploaded`); } }
    exportToJSON() { const backup = { version: "3.0", exportDate: new Date().toISOString(), data: this.data }; const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `studybaby_backup.json`; a.click(); this.showToast('backup saved'); }
    importFromJSON(file) { const reader = new FileReader(); reader.onload = async (e) => { try { const imported = JSON.parse(e.target.result); if (imported.data?.semesters) { if (confirm('replace current data?')) { this.data = imported.data; await this.saveDataToDB(); this.currentSemesterId = this.data.semesters[0]?.id || null; this.selectedSubjectId = null; this.renderSemesterSelector(); this.renderSubjects(); this.loadSemesterNotebook(); document.getElementById('subjectFilesArea').style.display = 'none'; this.showToast('restored!'); } } else this.showToast('invalid file'); } catch(err) { this.showToast('error'); } }; reader.readAsText(file); }
    viewNotebookSummary() { const sem = this.getCurrentSemester(); if (!sem) { this.showToast('No semester selected'); return; } let notebookHtml = `<div style="background:#fff9f0; border-radius:32px; padding:1.5rem;"><h2 style="color:#db2777;"><i class="fas fa-book"></i> ${this.escape(sem.name)} - Notebook Summary</h2><hr>`;
    if (sem.semesterNotebook) notebookHtml += `<div style="margin:1rem 0;"><h3>📓 Global Semester Notebook</h3><div style="background:#ffeef4; border-radius:24px; padding:1rem;">${this.escape(sem.semesterNotebook)}</div></div>`;
    sem.subjects.forEach(sub => { if (sub.notebookNotes && sub.notebookNotes.trim()) { notebookHtml += `<div style="margin:1rem 0;"><h3>📘 ${this.escape(sub.name)}</h3><div style="background:#fff0f5; border-radius:24px; padding:1rem;">${this.escape(sub.notebookNotes)}</div></div>`; } });
    notebookHtml += `</div>`;
    document.getElementById('semesterSummary').innerHTML = notebookHtml; this.showToast('📖 Notebook summary view ready'); }
    setupTabs() { document.querySelectorAll('.tab-btn').forEach(btn => { btn.addEventListener('click', (e) => { const tabId = btn.dataset.tab; document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.tab-content').forEach(tab => tab.classList.remove('active-tab')); document.getElementById(tabId).classList.add('active-tab'); }); }); }
    attachEventListeners() {
        document.getElementById('semesterSelector')?.addEventListener('change', (e) => { if (e.target.value) { this.currentSemesterId = parseInt(e.target.value); this.selectedSubjectId = null; this.renderSubjects(); this.loadSemesterNotebook(); document.getElementById('subjectFilesArea').style.display = 'none'; document.getElementById('selectedSubjectInfo').innerHTML = '<div style="padding:1rem;">🍬 pick a subject</div>'; } });
        document.getElementById('newSemesterBtn')?.addEventListener('click', () => { const name = prompt('semester name?'); if (name) this.addSemester(name); });
        document.getElementById('deleteSemesterBtn')?.addEventListener('click', () => this.deleteCurrentSemester());
        document.getElementById('editSemesterBtn')?.addEventListener('click', () => this.editSemesterName());
        document.getElementById('addSubjectBtn')?.addEventListener('click', () => { const name = document.getElementById('newSubjectName')?.value || ''; const comp = document.getElementById('completionType')?.value || 'Exam only'; this.addSubject(name, comp); });
        const fileUpload = document.getElementById('fileUpload'), uploadZone = document.getElementById('uploadZone');
        if (fileUpload) fileUpload.addEventListener('change', (e) => { if (e.target.files.length) this.handleFileUpload(e.target.files); e.target.value = ''; });
        if (uploadZone) { uploadZone.addEventListener('click', () => fileUpload?.click()); uploadZone.addEventListener('dragover', (e) => e.preventDefault()); uploadZone.addEventListener('drop', (e) => { e.preventDefault(); const files = Array.from(e.dataTransfer.files); if (files.length) this.handleFileUpload(files); }); }
        document.getElementById('saveSubjectNotesBtn')?.addEventListener('click', () => this.saveSubjectNotes());
        document.getElementById('saveSubjectNotebookBtn')?.addEventListener('click', () => this.saveSubjectNotebook());
        document.getElementById('saveSemesterNotebookBtn')?.addEventListener('click', () => this.saveSemesterNotebook());
        document.getElementById('generateSemesterSummaryBtn')?.addEventListener('click', () => this.generateSummary());
        document.getElementById('exportSummaryBtn')?.addEventListener('click', () => this.exportSummary());
        document.getElementById('exportDataBtn')?.addEventListener('click', () => this.exportToJSON());
        document.getElementById('importDataBtn')?.addEventListener('click', () => { const inp = document.createElement('input'); inp.type = 'file'; inp.accept = '.json'; inp.onchange = (e) => { if (e.target.files.length) this.importFromJSON(e.target.files[0]); }; inp.click(); });
        document.getElementById('openFilesViewBtn')?.addEventListener('click', () => this.openFilesByLanguage());
        document.getElementById('viewNotebookSummaryBtn')?.addEventListener('click', () => this.viewNotebookSummary());
        document.getElementById('closeModalBtn')?.addEventListener('click', () => this.closeModals());
        document.getElementById('closeLangModalBtn')?.addEventListener('click', () => this.closeModals());
        window.addEventListener('click', (e) => { if (e.target.classList?.contains('modal-cute')) this.closeModals(); });
    }
}
window.addEventListener('DOMContentLoaded', () => { new StudyBuddy(); });